[package]
name = "goon_proc_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.78"
syn = { version="1.0", features = ["full"]}
quote = "1.0"


[lib]
proc_macro = true

